site_name: Documentation
site_description: All the notes that I may need for my setup time to time.
site_author: myxi
docs_dir: docs/
repo_name: 'eeriemyxi/dotfiles'
repo_url: 'https://github.com/eeriemyxi/dotfiles'
nav:
    - Home: index.md
theme:
  name: 'material'
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
