window-scale=0.500

ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]
ytdl-raw-options=cookies=/home/myxi/Downloads/www.youtube.com_cookies.txt


hwdec=auto
profile=high-quality
video-sync=display-resample
# script-opts-append=ytdl_hook-try_ytdl_first=yes
script-opts-append=script-opts=ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"
cache=yes
demuxer-max-bytes=25MiB

# vf=format=yuv420p,vapoursynth=~~/motion.vpy:4:4

audio-channels=stereo
af="lowshelf=frequency=100:gain=-2.5,dynaudnorm=compress=27.0:gausssize=53"
