# *** OPTIONS

# Set theme
colorscheme cosy-gruvbox

# Width of a tab
set-option global tabstop 4

# Indent with 4 spaces
set-option global indentwidth 4

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

# Display the status bar on top
set-option global ui_options ncurses_status_on_top=true

# Enable auto reload
set-option global autoreload yes

# Disable startup changelog
set-option global startup_info_version 10000000000

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Change cursor color based on mode
hook global ModeChange .*:normal %{ set-face window PrimaryCursor rgb:fbf1c7,red }
hook global ModeChange .*:insert  %{ set-face window PrimaryCursor rgb:282828,rgb:fbf1c7+fg }

# *** PACKAGES

# Reasymotion
set-option global reasymotion_keys sfjklodwmbuyvrgtaqpcxz

# Raindow brackets
hook global WinCreate .* %{ rainbow-enable-window }

# Clipboard manager
hook global WinCreate .* %{ kakboard-enable }

# Buffered files
define-command shell-eval %{
    nop %sh{
        eval "$kak_reg_dot"
    }
}

hook global BufSetOption "filetype=%opt{files_browse_buffer}" %{
    map buffer normal '<ret>' ': files-cd<ret>'
    map buffer normal '<backspace>' ': files-cd-parent<ret>'
    map buffer normal 'm' ": files-add-entry-to-selection<ret>"
    map buffer normal 'M' ": files-add-cwd-to-selection<ret>"
    map buffer normal '.' ": files-toggle-show_hidden<ret>"
    map buffer normal '\' ": files-toggle-long_format<ret>"
    map buffer normal 'r' ": files-redraw-browser<ret>"
    map buffer normal 'S' ": files-focus-selections<ret>"
    map buffer normal 't' ": files-open-in-terminal<ret>"
}

hook global BufSetOption "filetype=%opt{files_selection_buffer}" %{
    map buffer normal <ret> ': shell-eval<ret>'
}

# Tabs
set-option global tabs_modelinefmt '%val{cursor_line}:%val{cursor_char_column} {{mode_info}} '
set-option global tabs_options --minified
map global tabs a "ga" -docstring "↔ alternate"
map global tabs h ": tabs-command prev<ret>" -docstring "← prev"
map global tabs i ": tabs-command next<ret>" -docstring "→ next"
map global tabs e ": tabs-command first<ret>" -docstring "↑ first"
map global tabs n ": tabs-command last<ret>" -docstring "↓ last"

# UI.kak
hook global WinCreate .* %{
    ui-line-numbers-toggle
    ui-cursorline-toggle
    ui-trailing-spaces-toggle
    ui-matching-toggle
    ui-search-toggle
    ui-todos-toggle
}

# Surrounder
declare-user-mode surround
map global surround s ':surround<ret>' -docstring 'surround'
map global surround c ':change-surround<ret>' -docstring 'change'
map global surround d ':delete-surround<ret>' -docstring 'delete'
map global surround t ':select-surrounding-tag<ret>' -docstring 'select tag'

# Custom mapping
hook global InsertChar h %{ try %{
  exec -draft hH <a-k>hh<ret> d
  exec <esc>
  set-face window PrimaryCursor default,red
}}

# Custom user mode (<space>)
map global user x ":write-all-quit<ret>" -docstring "save and quit"
map global user s ":enter-user-mode surround<ret>" -docstring "surrounder"
map global user t ":enter-user-mode tabs<ret>" -docstring "tab manager"
map global user f ":fzf-mode<ret>" -docstring "file nav"

