;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-char
        backward-delete-char-untabify
        boon-two-char-exit-insert-state
        forward-char
        move-end-of-line
        my/backward-delete-word
        python-indent-dedent-line-backspace
        self-insert-command
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        insert-register
        next-line
        previous-line
        ))
