[tools]
python = "3.11"
"nodejs" = "23.0.0"
"deno" = "2.1.1"
"zig" = "0.13.0"
"lua" = "5.4.7"
"bun" = "latest"
"uv" = "latest"
"pipx" = "latest"
"ruff" = "latest"
# "npm:vmd" = "latest"
# "npm:live-server" = "latest"
# "npm:localtunnel" = "latest"
# "npm:typescript-language-server" = "latest"
# "npm:typescript" = "latest"
"pipx:eeriemyxi/mechvibes-lite" = "latest"
"pipx:eeriemyxi/doty" = "latest"
"pipx:eeriemyxi/lismi" = "latest"
"pipx:eeriemyxi/nimo" = "latest"
"pipx:eeriemyxi/lyto" = "latest"
"pipx:eeriemyxi/vert" = "v0.2.6"
"pipx:isort" = "latest"
"pipx:black" = "latest"
"pipx:python-lsp-server" = "latest"
"pipx:pyright" = "latest"
"pipx:mkdocs" = "latest"
usage = "latest"
"npm:vmd" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.npm]
bun = true
